name: CI - NestJS Quality Gate

on:
  pull_request:
    branches:
      - main
      - dev
      - hml

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Lint check
        run: npm run lint

      - name: Run tests with coverage
        run: npm run test:cov

      - name: Validate 80% test coverage
        run: |
          COVERAGE=$(node -p "require('./coverage/coverage-summary.json').total.lines.pct")
          echo "Test Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 50" | bc -l) )); then
            echo "❌ Cobertura abaixo de 80%"
            exit 1
          fi

      - name: Validate no console.* usage
        run: |
          if grep -r --include=*.ts "console\\." ./src; then
            echo "❌ Uso de console.log ou console.table encontrado"
            exit 1
          fi

      - name: Validate version bump
        run: |
          git fetch origin main
          BASE_VERSION=$(git show origin/main:package.json | jq -r .version)
          CURRENT_VERSION=$(jq -r .version package.json)

          echo "Base: $BASE_VERSION, Atual: $CURRENT_VERSION"

          if [ "$BASE_VERSION" = "$CURRENT_VERSION" ]; then
            echo "❌ Versão do package.json precisa ser atualizada."
            exit 1
          fi

      - name: Run SonarQube analysis
        env:
          SONAR_KEY: ${{ secrets.SONAR_KEY }}
        run: |
          npm install -g sonar-scanner
          sonar-scanner
